# Generated by Django 5.1.2 on 2025-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoolnii_ner', models.CharField(max_length=255)),
                ('tuuhii_edd', models.TextField()),
                ('ilchleg', models.IntegerField()),
                ('ogoh_hemjee', models.CharField(max_length=100)),
            ],
        ),
    ]
