# Generated by Django 5.1.2 on 2025-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_foodmenu_rename_ilchleg_food_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('breakfast_day1', models.CharField(max_length=255)),
                ('snack_day1', models.CharField(max_length=255)),
                ('dinner_day1', models.CharField(max_length=255)),
                ('total_calories_day1', models.IntegerField()),
                ('breakfast_day2', models.CharField(max_length=255)),
                ('snack_day2', models.CharField(max_length=255)),
                ('dinner_day2', models.CharField(max_length=255)),
                ('total_calories_day2', models.IntegerField()),
                ('breakfast_day3', models.CharField(max_length=255)),
                ('snack_day3', models.CharField(max_length=255)),
                ('dinner_day3', models.CharField(max_length=255)),
                ('total_calories_day3', models.IntegerField()),
                ('breakfast_day4', models.CharField(max_length=255)),
                ('snack_day4', models.CharField(max_length=255)),
                ('dinner_day4', models.CharField(max_length=255)),
                ('total_calories_day4', models.IntegerField()),
                ('breakfast_day5', models.CharField(max_length=255)),
                ('snack_day5', models.CharField(max_length=255)),
                ('dinner_day5', models.CharField(max_length=255)),
                ('total_calories_day5', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.FloatField(),
        ),
    ]
