# Generated by Django 5.1.2 on 2025-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu_alter_food_name_alter_food_serving_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='breakfast_day1',
            new_name='breakfast',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='total_calories_day1',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='breakfast_day2',
            new_name='lunch',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='breakfast_day3',
            new_name='snack',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='breakfast_day4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='breakfast_day5',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner_day1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner_day2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner_day3',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner_day4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner_day5',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack_day1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack_day2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack_day3',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack_day4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='snack_day5',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_calories_day2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_calories_day3',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_calories_day4',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_calories_day5',
        ),
    ]
