# Generated by Django 5.1.2 on 2025-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='ilchleg',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='tuuhii_edd',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='ogoh_hemjee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='hoolnii_ner',
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
